//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace black_lotus.dbConnection {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback createConnOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback addSalesmanOperationCompleted;
        
        private System.Threading.SendOrPostCallback addFlowersOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateFlowersOperationCompleted;
        
        private System.Threading.SendOrPostCallback sellFlowersOperationCompleted;
        
        private System.Threading.SendOrPostCallback addcustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback retriveCustomerDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback retriveFlowerDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback retriveFlowerDataToAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback viewCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback viewSalesmenOperationCompleted;
        
        private System.Threading.SendOrPostCallback viewPurchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback viewCatOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCategoriesToComboOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrevwLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback addcategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteCatOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteCatfromFlowOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::black_lotus.Properties.Settings.Default.black_lotus_dbConnection_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event createConnCompletedEventHandler createConnCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event addSalesmanCompletedEventHandler addSalesmanCompleted;
        
        /// <remarks/>
        public event addFlowersCompletedEventHandler addFlowersCompleted;
        
        /// <remarks/>
        public event updateFlowersCompletedEventHandler updateFlowersCompleted;
        
        /// <remarks/>
        public event sellFlowersCompletedEventHandler sellFlowersCompleted;
        
        /// <remarks/>
        public event addcustomerCompletedEventHandler addcustomerCompleted;
        
        /// <remarks/>
        public event retriveCustomerDataCompletedEventHandler retriveCustomerDataCompleted;
        
        /// <remarks/>
        public event retriveFlowerDataCompletedEventHandler retriveFlowerDataCompleted;
        
        /// <remarks/>
        public event retriveFlowerDataToAddCompletedEventHandler retriveFlowerDataToAddCompleted;
        
        /// <remarks/>
        public event viewCustomersCompletedEventHandler viewCustomersCompleted;
        
        /// <remarks/>
        public event viewSalesmenCompletedEventHandler viewSalesmenCompleted;
        
        /// <remarks/>
        public event viewPurchesCompletedEventHandler viewPurchesCompleted;
        
        /// <remarks/>
        public event viewCatCompletedEventHandler viewCatCompleted;
        
        /// <remarks/>
        public event getCategoriesToComboCompletedEventHandler getCategoriesToComboCompleted;
        
        /// <remarks/>
        public event retrevwLoginCompletedEventHandler retrevwLoginCompleted;
        
        /// <remarks/>
        public event addcategoryCompletedEventHandler addcategoryCompleted;
        
        /// <remarks/>
        public event deleteCatCompletedEventHandler deleteCatCompleted;
        
        /// <remarks/>
        public event deleteCatfromFlowCompletedEventHandler deleteCatfromFlowCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createConn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool createConn() {
            object[] results = this.Invoke("createConn", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void createConnAsync() {
            this.createConnAsync(null);
        }
        
        /// <remarks/>
        public void createConnAsync(object userState) {
            if ((this.createConnOperationCompleted == null)) {
                this.createConnOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateConnOperationCompleted);
            }
            this.InvokeAsync("createConn", new object[0], this.createConnOperationCompleted, userState);
        }
        
        private void OncreateConnOperationCompleted(object arg) {
            if ((this.createConnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createConnCompleted(this, new createConnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool login(string name, string pass) {
            object[] results = this.Invoke("login", new object[] {
                        name,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string name, string pass) {
            this.loginAsync(name, pass, null);
        }
        
        /// <remarks/>
        public void loginAsync(string name, string pass, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        name,
                        pass}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addSalesman", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addSalesman(string name, string tp, string age, string addr) {
            object[] results = this.Invoke("addSalesman", new object[] {
                        name,
                        tp,
                        age,
                        addr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addSalesmanAsync(string name, string tp, string age, string addr) {
            this.addSalesmanAsync(name, tp, age, addr, null);
        }
        
        /// <remarks/>
        public void addSalesmanAsync(string name, string tp, string age, string addr, object userState) {
            if ((this.addSalesmanOperationCompleted == null)) {
                this.addSalesmanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddSalesmanOperationCompleted);
            }
            this.InvokeAsync("addSalesman", new object[] {
                        name,
                        tp,
                        age,
                        addr}, this.addSalesmanOperationCompleted, userState);
        }
        
        private void OnaddSalesmanOperationCompleted(object arg) {
            if ((this.addSalesmanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addSalesmanCompleted(this, new addSalesmanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addFlowers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addFlowers(string cat, string name, string qunt, string ppu) {
            object[] results = this.Invoke("addFlowers", new object[] {
                        cat,
                        name,
                        qunt,
                        ppu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addFlowersAsync(string cat, string name, string qunt, string ppu) {
            this.addFlowersAsync(cat, name, qunt, ppu, null);
        }
        
        /// <remarks/>
        public void addFlowersAsync(string cat, string name, string qunt, string ppu, object userState) {
            if ((this.addFlowersOperationCompleted == null)) {
                this.addFlowersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddFlowersOperationCompleted);
            }
            this.InvokeAsync("addFlowers", new object[] {
                        cat,
                        name,
                        qunt,
                        ppu}, this.addFlowersOperationCompleted, userState);
        }
        
        private void OnaddFlowersOperationCompleted(object arg) {
            if ((this.addFlowersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addFlowersCompleted(this, new addFlowersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateFlowers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateFlowers(string cat, string name, string qunt, string ppu, string id) {
            object[] results = this.Invoke("updateFlowers", new object[] {
                        cat,
                        name,
                        qunt,
                        ppu,
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateFlowersAsync(string cat, string name, string qunt, string ppu, string id) {
            this.updateFlowersAsync(cat, name, qunt, ppu, id, null);
        }
        
        /// <remarks/>
        public void updateFlowersAsync(string cat, string name, string qunt, string ppu, string id, object userState) {
            if ((this.updateFlowersOperationCompleted == null)) {
                this.updateFlowersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateFlowersOperationCompleted);
            }
            this.InvokeAsync("updateFlowers", new object[] {
                        cat,
                        name,
                        qunt,
                        ppu,
                        id}, this.updateFlowersOperationCompleted, userState);
        }
        
        private void OnupdateFlowersOperationCompleted(object arg) {
            if ((this.updateFlowersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateFlowersCompleted(this, new updateFlowersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sellFlowers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool sellFlowers(string cid, string cname, string ctp, string caddr, string fid, string fcat, string fname, string qunt, string tot) {
            object[] results = this.Invoke("sellFlowers", new object[] {
                        cid,
                        cname,
                        ctp,
                        caddr,
                        fid,
                        fcat,
                        fname,
                        qunt,
                        tot});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void sellFlowersAsync(string cid, string cname, string ctp, string caddr, string fid, string fcat, string fname, string qunt, string tot) {
            this.sellFlowersAsync(cid, cname, ctp, caddr, fid, fcat, fname, qunt, tot, null);
        }
        
        /// <remarks/>
        public void sellFlowersAsync(string cid, string cname, string ctp, string caddr, string fid, string fcat, string fname, string qunt, string tot, object userState) {
            if ((this.sellFlowersOperationCompleted == null)) {
                this.sellFlowersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsellFlowersOperationCompleted);
            }
            this.InvokeAsync("sellFlowers", new object[] {
                        cid,
                        cname,
                        ctp,
                        caddr,
                        fid,
                        fcat,
                        fname,
                        qunt,
                        tot}, this.sellFlowersOperationCompleted, userState);
        }
        
        private void OnsellFlowersOperationCompleted(object arg) {
            if ((this.sellFlowersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sellFlowersCompleted(this, new sellFlowersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addcustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addcustomer(string name, string tp, string email, string addr) {
            object[] results = this.Invoke("addcustomer", new object[] {
                        name,
                        tp,
                        email,
                        addr});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addcustomerAsync(string name, string tp, string email, string addr) {
            this.addcustomerAsync(name, tp, email, addr, null);
        }
        
        /// <remarks/>
        public void addcustomerAsync(string name, string tp, string email, string addr, object userState) {
            if ((this.addcustomerOperationCompleted == null)) {
                this.addcustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddcustomerOperationCompleted);
            }
            this.InvokeAsync("addcustomer", new object[] {
                        name,
                        tp,
                        email,
                        addr}, this.addcustomerOperationCompleted, userState);
        }
        
        private void OnaddcustomerOperationCompleted(object arg) {
            if ((this.addcustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addcustomerCompleted(this, new addcustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retriveCustomerData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retriveCustomerData(string id) {
            object[] results = this.Invoke("retriveCustomerData", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retriveCustomerDataAsync(string id) {
            this.retriveCustomerDataAsync(id, null);
        }
        
        /// <remarks/>
        public void retriveCustomerDataAsync(string id, object userState) {
            if ((this.retriveCustomerDataOperationCompleted == null)) {
                this.retriveCustomerDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretriveCustomerDataOperationCompleted);
            }
            this.InvokeAsync("retriveCustomerData", new object[] {
                        id}, this.retriveCustomerDataOperationCompleted, userState);
        }
        
        private void OnretriveCustomerDataOperationCompleted(object arg) {
            if ((this.retriveCustomerDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retriveCustomerDataCompleted(this, new retriveCustomerDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retriveFlowerData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retriveFlowerData(string id) {
            object[] results = this.Invoke("retriveFlowerData", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retriveFlowerDataAsync(string id) {
            this.retriveFlowerDataAsync(id, null);
        }
        
        /// <remarks/>
        public void retriveFlowerDataAsync(string id, object userState) {
            if ((this.retriveFlowerDataOperationCompleted == null)) {
                this.retriveFlowerDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretriveFlowerDataOperationCompleted);
            }
            this.InvokeAsync("retriveFlowerData", new object[] {
                        id}, this.retriveFlowerDataOperationCompleted, userState);
        }
        
        private void OnretriveFlowerDataOperationCompleted(object arg) {
            if ((this.retriveFlowerDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retriveFlowerDataCompleted(this, new retriveFlowerDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retriveFlowerDataToAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retriveFlowerDataToAdd() {
            object[] results = this.Invoke("retriveFlowerDataToAdd", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retriveFlowerDataToAddAsync() {
            this.retriveFlowerDataToAddAsync(null);
        }
        
        /// <remarks/>
        public void retriveFlowerDataToAddAsync(object userState) {
            if ((this.retriveFlowerDataToAddOperationCompleted == null)) {
                this.retriveFlowerDataToAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretriveFlowerDataToAddOperationCompleted);
            }
            this.InvokeAsync("retriveFlowerDataToAdd", new object[0], this.retriveFlowerDataToAddOperationCompleted, userState);
        }
        
        private void OnretriveFlowerDataToAddOperationCompleted(object arg) {
            if ((this.retriveFlowerDataToAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retriveFlowerDataToAddCompleted(this, new retriveFlowerDataToAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/viewCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string viewCustomers() {
            object[] results = this.Invoke("viewCustomers", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void viewCustomersAsync() {
            this.viewCustomersAsync(null);
        }
        
        /// <remarks/>
        public void viewCustomersAsync(object userState) {
            if ((this.viewCustomersOperationCompleted == null)) {
                this.viewCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnviewCustomersOperationCompleted);
            }
            this.InvokeAsync("viewCustomers", new object[0], this.viewCustomersOperationCompleted, userState);
        }
        
        private void OnviewCustomersOperationCompleted(object arg) {
            if ((this.viewCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.viewCustomersCompleted(this, new viewCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/viewSalesmen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string viewSalesmen() {
            object[] results = this.Invoke("viewSalesmen", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void viewSalesmenAsync() {
            this.viewSalesmenAsync(null);
        }
        
        /// <remarks/>
        public void viewSalesmenAsync(object userState) {
            if ((this.viewSalesmenOperationCompleted == null)) {
                this.viewSalesmenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnviewSalesmenOperationCompleted);
            }
            this.InvokeAsync("viewSalesmen", new object[0], this.viewSalesmenOperationCompleted, userState);
        }
        
        private void OnviewSalesmenOperationCompleted(object arg) {
            if ((this.viewSalesmenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.viewSalesmenCompleted(this, new viewSalesmenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/viewPurches", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string viewPurches() {
            object[] results = this.Invoke("viewPurches", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void viewPurchesAsync() {
            this.viewPurchesAsync(null);
        }
        
        /// <remarks/>
        public void viewPurchesAsync(object userState) {
            if ((this.viewPurchesOperationCompleted == null)) {
                this.viewPurchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnviewPurchesOperationCompleted);
            }
            this.InvokeAsync("viewPurches", new object[0], this.viewPurchesOperationCompleted, userState);
        }
        
        private void OnviewPurchesOperationCompleted(object arg) {
            if ((this.viewPurchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.viewPurchesCompleted(this, new viewPurchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/viewCat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string viewCat() {
            object[] results = this.Invoke("viewCat", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void viewCatAsync() {
            this.viewCatAsync(null);
        }
        
        /// <remarks/>
        public void viewCatAsync(object userState) {
            if ((this.viewCatOperationCompleted == null)) {
                this.viewCatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnviewCatOperationCompleted);
            }
            this.InvokeAsync("viewCat", new object[0], this.viewCatOperationCompleted, userState);
        }
        
        private void OnviewCatOperationCompleted(object arg) {
            if ((this.viewCatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.viewCatCompleted(this, new viewCatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCategoriesToCombo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCategoriesToCombo() {
            object[] results = this.Invoke("getCategoriesToCombo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCategoriesToComboAsync() {
            this.getCategoriesToComboAsync(null);
        }
        
        /// <remarks/>
        public void getCategoriesToComboAsync(object userState) {
            if ((this.getCategoriesToComboOperationCompleted == null)) {
                this.getCategoriesToComboOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCategoriesToComboOperationCompleted);
            }
            this.InvokeAsync("getCategoriesToCombo", new object[0], this.getCategoriesToComboOperationCompleted, userState);
        }
        
        private void OngetCategoriesToComboOperationCompleted(object arg) {
            if ((this.getCategoriesToComboCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCategoriesToComboCompleted(this, new getCategoriesToComboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retrevwLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string retrevwLogin() {
            object[] results = this.Invoke("retrevwLogin", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void retrevwLoginAsync() {
            this.retrevwLoginAsync(null);
        }
        
        /// <remarks/>
        public void retrevwLoginAsync(object userState) {
            if ((this.retrevwLoginOperationCompleted == null)) {
                this.retrevwLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrevwLoginOperationCompleted);
            }
            this.InvokeAsync("retrevwLogin", new object[0], this.retrevwLoginOperationCompleted, userState);
        }
        
        private void OnretrevwLoginOperationCompleted(object arg) {
            if ((this.retrevwLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrevwLoginCompleted(this, new retrevwLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addcategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addcategory(string cat) {
            object[] results = this.Invoke("addcategory", new object[] {
                        cat});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addcategoryAsync(string cat) {
            this.addcategoryAsync(cat, null);
        }
        
        /// <remarks/>
        public void addcategoryAsync(string cat, object userState) {
            if ((this.addcategoryOperationCompleted == null)) {
                this.addcategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddcategoryOperationCompleted);
            }
            this.InvokeAsync("addcategory", new object[] {
                        cat}, this.addcategoryOperationCompleted, userState);
        }
        
        private void OnaddcategoryOperationCompleted(object arg) {
            if ((this.addcategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addcategoryCompleted(this, new addcategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteCat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteCat(string name) {
            object[] results = this.Invoke("deleteCat", new object[] {
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteCatAsync(string name) {
            this.deleteCatAsync(name, null);
        }
        
        /// <remarks/>
        public void deleteCatAsync(string name, object userState) {
            if ((this.deleteCatOperationCompleted == null)) {
                this.deleteCatOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteCatOperationCompleted);
            }
            this.InvokeAsync("deleteCat", new object[] {
                        name}, this.deleteCatOperationCompleted, userState);
        }
        
        private void OndeleteCatOperationCompleted(object arg) {
            if ((this.deleteCatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCatCompleted(this, new deleteCatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteCatfromFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteCatfromFlow(string name) {
            object[] results = this.Invoke("deleteCatfromFlow", new object[] {
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteCatfromFlowAsync(string name) {
            this.deleteCatfromFlowAsync(name, null);
        }
        
        /// <remarks/>
        public void deleteCatfromFlowAsync(string name, object userState) {
            if ((this.deleteCatfromFlowOperationCompleted == null)) {
                this.deleteCatfromFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteCatfromFlowOperationCompleted);
            }
            this.InvokeAsync("deleteCatfromFlow", new object[] {
                        name}, this.deleteCatfromFlowOperationCompleted, userState);
        }
        
        private void OndeleteCatfromFlowOperationCompleted(object arg) {
            if ((this.deleteCatfromFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCatfromFlowCompleted(this, new deleteCatfromFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void createConnCompletedEventHandler(object sender, createConnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createConnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createConnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addSalesmanCompletedEventHandler(object sender, addSalesmanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addSalesmanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addSalesmanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addFlowersCompletedEventHandler(object sender, addFlowersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addFlowersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addFlowersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updateFlowersCompletedEventHandler(object sender, updateFlowersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateFlowersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateFlowersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sellFlowersCompletedEventHandler(object sender, sellFlowersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sellFlowersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sellFlowersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addcustomerCompletedEventHandler(object sender, addcustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addcustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addcustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void retriveCustomerDataCompletedEventHandler(object sender, retriveCustomerDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retriveCustomerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retriveCustomerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void retriveFlowerDataCompletedEventHandler(object sender, retriveFlowerDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retriveFlowerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retriveFlowerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void retriveFlowerDataToAddCompletedEventHandler(object sender, retriveFlowerDataToAddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retriveFlowerDataToAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retriveFlowerDataToAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void viewCustomersCompletedEventHandler(object sender, viewCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class viewCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal viewCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void viewSalesmenCompletedEventHandler(object sender, viewSalesmenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class viewSalesmenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal viewSalesmenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void viewPurchesCompletedEventHandler(object sender, viewPurchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class viewPurchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal viewPurchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void viewCatCompletedEventHandler(object sender, viewCatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class viewCatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal viewCatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getCategoriesToComboCompletedEventHandler(object sender, getCategoriesToComboCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCategoriesToComboCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCategoriesToComboCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void retrevwLoginCompletedEventHandler(object sender, retrevwLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrevwLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrevwLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addcategoryCompletedEventHandler(object sender, addcategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addcategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addcategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteCatCompletedEventHandler(object sender, deleteCatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteCatfromFlowCompletedEventHandler(object sender, deleteCatfromFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCatfromFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCatfromFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591